config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, only: %i[index show new create destroy] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, presence: true, length: { minimum: 6 }
  validates :list, presence: true
  validates :movie_id, uniqueness: { scope: :list_id, message: 'is already in the list' }
  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    # we need @list in our `simple_form_for`
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to @list
    else
      render 'new'
    end
  end

  # DELETE 'plants/:id'
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  # /lists/:id
  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params_list)

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def params_list
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h2>List's bookmarks</h2>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Add Movie" %>
<% end %>



<%= link_to 'Back', lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'My lists', @list, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add List", new_list_path, class: "nav-link" %>
          </li>
          </ul>
      </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>My beautiful <strong>Movie</strong> <strong>List</strong>!</h1>
    <p>Welcome again, Buddy!</p>
    <a class="btn btn-flat" href="https://www.google.com/">Exit now</a>
  </div>
</div>

<h2> My lists:</h2>

<div class="cards">
    <% @lists.each do |list| %>
      <div class="card mb-5" >
        <div class="card-body">
          <img src="..;" class="card-img-top" alt="...">
          <p class="list-name"><%= link_to list.name, list %></p>
        </div>
      </div>
    <% end %>
</div>
<%= link_to 'Create a movie List', new_list_path, class: "btn btn-primary ml 3" %>

app/views/lists/new.html.erb
<h1> New List</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit "add a list" %>
<% end %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<% @list.bookmarks.each do |bookmark| %>
  <%= bookmark.movie.title %>
  <%= bookmark.comment %>
  <%# <%= link_to "delete this movie", list_bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>
<hr>
<%= link_to 'Add Movie', new_list_bookmark_path(@list) %> |
<%= link_to 'Back', lists_path %> |
<%= link_to "delete this list", list_path(@list), method: :delete, data: { confirm: "Are you sure?" } %>